export const quotes: string[] = [
  "Carpe diem… but maybe after coffee.",
  "Fake it till you make it — then keep faking it.",
  "You survived 100% of your worst days. Impressive.",
  "Be a warrior, not a worrier. Or at least nap first.",
  "Dream big. Nap bigger.",
  "Do it for your future self (they’re tired of waiting).",
  "If at first you don’t succeed, redefine success.",
  "Stay positive. Except for negative numbers, those are fine.",
  "Productivity is just procrastination with confidence.",
  "You got this. Probably.",
  "One step at a time unless there’s pizza.",
  "Believe in yourself like autocorrect believes in chaos.",
  "Today is a good day to pretend you know what you’re doing.",
  "Be the reason your phone battery is low.",
  "Work hard so your dog can have a better life.",
  "The early bird gets the worm, but the second mouse gets the cheese.",
  "Don’t quit your daydream.",
  "Mistakes were made. Lessons were optional.",
  "Smile — it confuses people.",
  "If nothing goes right, go left.",
  "Success is mostly showing up and looking busy.",
  "Do more things that make you forget to check your phone.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Running late is my cardio.",
  "You are one snack away from a better mood.",
  "Think outside the box. Then recycle the box.",
  "Be yourself; everyone else is already tired.",
  "If stress burned calories, I’d be a superhero.",
  "Multitasking = messing up several things at once.",
  "Keep calm and pretend it’s on the roadmap.",
];
