export const quotes: string[] = [
  "Fånga dagen… men kanske efter kaffe.",
  "Fejka tills du lyckas — och fortsätt fejka.",
  "Du överlevde 100 % av dina värsta dagar. Imponerande.",
  "Var en krigare, inte en orolig typ. Eller ta åtminstone en tupplur först.",
  "Dröm stort. Sov större.",
  "Gör det för ditt framtida jag (de har väntat tillräckligt länge).",
  "Om du inte lyckas först, omdefiniera framgång.",
  "Håll dig positiv. Förutom med negativa tal, de är okej.",
  "Produktivitet är bara prokrastinering med självförtroende.",
  "Du klarar det. Troligen.",
  "Ett steg i taget, om det inte finns pizza.",
  "Tro på dig själv som autocorrect tror på kaos.",
  "Idag är en bra dag att låtsas att du vet vad du gör.",
  "Var anledningen till att ditt batteri är lågt.",
  "Jobba hårt så att din hund får ett bättre liv.",
  "Den tidiga fågeln får masken, men den andra musen får osten.",
  "Ge inte upp dina dagdrömmar.",
  "Misstag gjordes. Lärdomar var valfria.",
  "Le — det förvirrar folk.",
  "Om inget går rätt, gå åt vänster.",
  "Framgång är mest att dyka upp och se upptagen ut.",
  "Gör fler saker som får dig att glömma kolla telefonen.",
  "Vissa tar examen med utmärkelser, jag är bara hedrad att ta examen.",
  "Att vara sen är min träning.",
  "Du är ett mellanmål från ett bättre humör.",
  "Tänk utanför boxen. Sen återvinn boxen.",
  "Var dig själv; alla andra är redan trötta.",
  "Om stress brände kalorier skulle jag vara en superhjälte.",
  "Multitasking = röra till flera saker samtidigt.",
  "Behåll lugnet och låtsas att det är på planeringen.",
  "Bara fantasin sätter gränser",
];
